routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeCategoryController;
use App\Http\Controllers\Admin\AdvertisementController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\GovernorateController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\AreaController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\WelcomeController;
use App\Http\Controllers\Admin\ReportReasonController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\ComplainSuggestionController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\PropertiesController;
use App\Http\Controllers\Admin\CommercialAdvertisementsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){ return redirect()->route('admin.login'); });

Route::get('login', [AuthController::class, 'viewLoginPage'])->name('login');
Route::post('login', [AuthController::class, 'authenticate'])->name('authenticate');

Route::middleware('auth')->group(function (){
    Route::get('dashboard', [HomeController::class, 'reportStatistics'])->name('dashboard.index');

//    Route::post('categories/delete', [CategoryController::class, 'destroyAll'])->name('categories.destroyAll');
    Route::get('categories/status/{id}', [CategoryController::class, 'changeStatus'])->name('categories.changeStatus');
    Route::post('categories/excel', [CategoryController::class, 'excel'])->name('categories.excel');
    Route::resource('categories', CategoryController::class, ['except' => 'create','edit']);
    Route::post('category_fields/excel', [AttributeCategoryController::class, 'excel'])->name('category_fields.excel');
    Route::resource('category_fields', AttributeCategoryController::class, ['except' => 'create','edit']);
    Route::get('get-advertisement-types', [CategoryController::class, 'getAdvertisementsTypes'])->name('categories.get-advertisement-types');
    Route::post('get-advertisement-types', [CategoryController::class, 'addAdvertisementsTypes'])->name('categories.add-advertisement-types');
    Route::put('update-advertisement-types/{id}', [CategoryController::class, 'updateAdvertisementsTypes'])->name('categories.update-advertisement-types');
    Route::delete('delete-advertisement-types/{id}', [CategoryController::class, 'deleteAdvertisementsTypes'])->name('categories.delete-advertisement-types');

    Route::get('packages/status/{id}', [PackagesController::class, 'changeStatus'])->name('packages.changeStatus');
    Route::resource('packages', PackagesController::class, ['except' => 'create','edit']);
    Route::resource('property_fields', PropertiesController::class, ['except' => 'create', 'edit']);
    Route::post('property_fields/excel', [PropertiesController::class, 'excel'])->name('property_fields.excel');

    Route::get('advertisements/delete_image/{id}', [AdvertisementController::class, 'deleteImage'])->name('advertisements.deleteImage');
    Route::resource('advertisements', AdvertisementController::class, ['except' => 'show', 'store','create','edit']);

    Route::get('advertisements/reports/{advertisement}', [AdvertisementController::class, 'reportedAdvertisementsUpdate'])->name('advertisements.reports.update');
    Route::delete('advertisements/reports/destroy/{id}', [AdvertisementController::class, 'destroyReportedAdvertisements'])->name('advertisements.reports.destroy');

    Route::resource('comments', CommentController::class, ['except' => 'show', 'store','create','edit']);

    Route::resource('countries', CountryController::class, ['except' => 'show','create','edit']);
    Route::resource('governorates', GovernorateController::class, ['except' => 'show','create','edit']);
    Route::resource('cities', CityController::class, ['except' => 'show','create','edit']);
    Route::resource('areas', AreaController::class, ['except' => 'show','create','edit']);

    Route::resource('banners', BannerController::class, ['except' => 'show','create','edit']);

    Route::resource('settings', SettingController::class, ['except' => 'index','create','edit']);
    Route::resource('contact_us', ContactUsController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('complain_suggestions', ComplainSuggestionController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('welcomes', WelcomeController::class, ['except' => 'show','create','edit']);
    Route::resource('report_reasons', ReportReasonController::class, ['except' => 'show','create','edit']);

    Route::get('admins/status/{id}', [AdminController::class, 'changeStatus'])->name('admins.changeStatus');
    Route::delete('admins/history-log/{id}/delete', [AdminController::class, 'destroyHistoryLog'])->name('admins.destroyHistoryLog');
    Route::resource('admins', AdminController::class, ['except' => 'create','edit']);
    Route::get('admins/history/{id}', [AdminController::class,'loginHistory'])->name('admins.history');

    Route::post('users/notification/{id}', [UserController::class, 'sendNotification'])->name('users.sendNotification');
    Route::get('users/status/{id}', [UserController::class, 'changeStatus'])->name('users.changeStatus');
    Route::get('users/notification/status/{id}', [UserController::class, 'changeNotification'])->name('users.changeNotification');
    Route::resource('users', UserController::class, ['except' => 'show','create','edit']);

    Route::resource('companies', CompanyController::class, ['except' => 'create','edit']);
    Route::resource('commercial_advertisements', CommercialAdvertisementsController::class, ['except' => 'create','edit']);
    Route::get('commercial_advertisements/status/{id}', [CommercialAdvertisementsController::class, 'changeStatus'])->name('commercial_advertisements.changeStatus');
    Route::resource('notifications', NotificationController::class, ['except' => 'show','create','update','edit']);

    Route::resource('profile', ProfileController::class, ['except' => 'show','create','update','edit']);

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('set-locale/{locale}', function ($locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

app/Models/Area.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Area extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function translations()
    {
        return $this->hasMany(Area::class, 'translation_id');
    }

    public function translation()
    {
        return $this->hasOne(Area::class, 'translation_id');
    }
}

app/Http/Controllers/Admin/AreaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Areas\StoreAreaRequest;
use App\Http\Requests\Admin\Areas\UpdateAreaRequest;
use App\Models\Area;
use App\Models\City;

class AreaController extends Controller
{
    public function index()
    {
        $this->authorize('viewAny', Area::class);

        $cities = City::whereNull('translation_id')->get();

        return view('admin.locations.areas.index', compact('cities'));
    }

    public function store(StoreAreaRequest $request)
    {
        $this->authorize('create', Area::class);

        Area::create([
            'name'      => $request->name,
            'city_id'   => $request->city_id,
            'language'  => 'ar',
        ]);

        return back()->with('success', __('The action ran successfully!'));
    }

    public function update(UpdateAreaRequest $request, Area $area)
    {
        $this->authorize('update', Area::class);

        $area->update([
            'name'    => $request->edit_name,
            'city_id' => $request->edit_city_id,
        ]);

        return back()->with('success', __('The action ran successfully!'));
    }

    public function destroy($id)
    {
        $this->authorize('delete', Area::class);

        $area = Area::findOrFail($id);

        $area->delete();

        return back()->with('success', __('The action ran successfully!'));
    }
}

resources/views/admin/locations/areas/index.blade.php
@extends('layouts.admin', ['title' => __('Areas')])
@section('css')
    <!-- datatable style -->
    @include('admin.includes.datatable.style')
@endsection
@section('breadcrumb')
    <h3>{{__('Areas')}}</h3>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard.index')}}"><i data-feather="home"></i></a></li>
        <li class="breadcrumb-item active">{{__('Areas')}}</li>
    </ol>
@endsection
@section('button')
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createModal">
        <i class="fa fa-plus"></i>
        {{__('Add')}}
    </button>
@endsection
@section('content')

    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="datatable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>{{(__('Name'))}}</th>
                            <th>{{(__('City'))}}</th>
                            <th>{{(__('Actions'))}}</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Start create areas -->
    @component('admin.includes.modal')
        @slot('modalID')
            createModal
        @endslot
        @slot('modalTitle')
            {{__('Add')}}
        @endslot
        @slot('modalRoute')
            {{route('admin.areas.store')}}
        @endslot
        @slot('modalContent')
            <div class="row">
                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Name')}} <span style="color:red">*</span></label>
                    <input type="text" name="name" class="form-control" value="{{old('name')}}" placeholder="{{__('Name')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'name'])
                </div>

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="city_id">{{__('Cities')}} <span style="color:red">*</span></label>
                    <select class="form-control" name="city_id">
                        <option disabled selected>{{__('Select Action')}}</option>
                        @foreach($cities as $city)
                            <option value="{{$city->id}}">{{$city->name}}</option>
                        @endforeach
                    </select>
                    @include('admin.includes.alerts.error', ['input' => 'city_id'])
                </div>
            </div>

        @endslot
    @endcomponent
    <!-- End create areas -->

    <!-- Start edit areas -->
    @component('admin.includes.modal')
        @slot('modalID')
            editModal
        @endslot
        @slot('modalTitle')
            {{__('Edit')}}
        @endslot
        @slot('modalMethodPutOrDelete')
            @method('put')
        @endslot
        @slot('modalContent')
            <div class="row">
                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Name')}}</label>
                    <input type="text" id="e_name" name="edit_name" class="form-control" placeholder="{{__('Name arabic')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'edit_name'])
                </div>

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="edit_city_id">{{__('Cities')}}</label>
                    <select class="form-control" name="edit_city_id" id="e_city_id">
                        <option disabled selected>{{__('Select Action')}}</option>
                        @foreach($cities as $city)
                            <option value="{{$city->id}}">{{$city->name}}</option>
                        @endforeach
                    </select>
                    @include('admin.includes.alerts.error', ['input' => 'edit_city_id'])
                </div>

            </div><!-- row -->
        @endslot
    @endcomponent
    <!-- End edit areas -->

    <!-- Start delete areas -->
    @component('admin.includes.modal')
        @slot('modalID')
            deleteModal
        @endslot
        @slot('modalTitle')
            {{__('Delete')}}
        @endslot
        @slot('modalMethodPutOrDelete')
            @method('delete')
        @endslot
        @slot('modalContent')
            <div class="text-center">
                <span class="text-danger font-16">
                    {{__('Are you sure you want to run this action?')}}
                </span>
            </div>
        @endslot
    @endcomponent
    <!-- End delete areas -->

@endsection

@section('script')
    @include('admin.includes.alerts.message')
    <!-- datatable scripts -->
    @include('admin.includes.datatable.scripts')
    <script>

        $(document).ready(function() {
            $("#datatable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": true,
                "processing": true, "serverSide": true, "order": [ [0, 'desc'] ],
                "ajax": {
                    url: "/api/datatable/areas",
                    "dataSrc": "data.data",
                },
                language: {
                    url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Arabic.json',
                },
                "columns": [
                    { data: 'id' },
                    { data: 'name' },
                    { data: 'city_name' },
                    { data: "operations", render: function (data, type, row) {

                        return  "<button title='{{__('Edit')}}' class='btn btn-warning btn-sm btn-condensed' onclick='openModalEdit("+JSON.stringify(row)+")' >" +
                            '<i class="fa fa-edit"></i>' +
                            '</button> ' +
                            '<button title="{{__('Delete')}}" class="btn btn-danger btn-sm btn-condensed" onclick=openModalDelete('+row.id+') >' +
                            '<i class="fa fa-trash"></i>' +
                            '</button>'
                        }
                    },
                ],
            });
        });

        function openModalEdit(area)
        {
            $('#e_name').val(area.name);
            $('#e_city_id').val(area.city_id);

            $('.action_form').attr('action', '{{route('admin.areas.update', '')}}' + '/' + area.id);
            $('#editModal').modal('show');
        }

        $('#editModal').on('hide.bs.modal', function() {
            $('.action_form').attr('action', '{{route('admin.areas.store')}}');
        })

        function openModalDelete(area_id)
        {
            $('.action_form').attr('action', '{{route('admin.areas.destroy', '')}}' + '/' + area_id);
            $('#deleteModal').modal('show');
        }

        $('#deleteModal').on('hide.bs.modal', function() {
            $('.action_form').attr('action', '{{route('admin.areas.store')}}');
        })
    </script>
@endsection