routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeCategoryController;
use App\Http\Controllers\Admin\AdvertisementController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\GovernorateController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\AreaController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\WelcomeController;
use App\Http\Controllers\Admin\ReportReasonController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\ComplainSuggestionController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\PropertiesController;
use App\Http\Controllers\Admin\CommercialAdvertisementsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){ return redirect()->route('admin.login'); });

Route::get('login', [AuthController::class, 'viewLoginPage'])->name('login');
Route::post('login', [AuthController::class, 'authenticate'])->name('authenticate');

Route::middleware('auth')->group(function (){
    Route::get('dashboard', [HomeController::class, 'reportStatistics'])->name('dashboard.index');

//    Route::post('categories/delete', [CategoryController::class, 'destroyAll'])->name('categories.destroyAll');
    Route::get('categories/status/{id}', [CategoryController::class, 'changeStatus'])->name('categories.changeStatus');
    Route::post('categories/excel', [CategoryController::class, 'excel'])->name('categories.excel');
    Route::resource('categories', CategoryController::class, ['except' => 'create','edit']);
    Route::post('category_fields/excel', [AttributeCategoryController::class, 'excel'])->name('category_fields.excel');
    Route::resource('category_fields', AttributeCategoryController::class, ['except' => 'create','edit']);
    Route::get('get-advertisement-types', [CategoryController::class, 'getAdvertisementsTypes'])->name('categories.get-advertisement-types');
    Route::post('get-advertisement-types', [CategoryController::class, 'addAdvertisementsTypes'])->name('categories.add-advertisement-types');
    Route::put('update-advertisement-types/{id}', [CategoryController::class, 'updateAdvertisementsTypes'])->name('categories.update-advertisement-types');
    Route::delete('delete-advertisement-types/{id}', [CategoryController::class, 'deleteAdvertisementsTypes'])->name('categories.delete-advertisement-types');

    Route::get('packages/status/{id}', [PackagesController::class, 'changeStatus'])->name('packages.changeStatus');
    Route::resource('packages', PackagesController::class, ['except' => 'create','edit']);
    Route::resource('property_fields', PropertiesController::class, ['except' => 'create', 'edit']);
    Route::post('property_fields/excel', [PropertiesController::class, 'excel'])->name('property_fields.excel');

    Route::get('advertisements/delete_image/{id}', [AdvertisementController::class, 'deleteImage'])->name('advertisements.deleteImage');
    Route::resource('advertisements', AdvertisementController::class, ['except' => 'show', 'store','create','edit']);

    Route::get('advertisements/reports/{advertisement}', [AdvertisementController::class, 'reportedAdvertisementsUpdate'])->name('advertisements.reports.update');
    Route::delete('advertisements/reports/destroy/{id}', [AdvertisementController::class, 'destroyReportedAdvertisements'])->name('advertisements.reports.destroy');

    Route::resource('comments', CommentController::class, ['except' => 'show', 'store','create','edit']);

    Route::resource('countries', CountryController::class, ['except' => 'show','create','edit']);
    Route::resource('governorates', GovernorateController::class, ['except' => 'show','create','edit']);
    Route::resource('cities', CityController::class, ['except' => 'show','create','edit']);
    Route::resource('areas', AreaController::class, ['except' => 'show','create','edit']);

    Route::resource('banners', BannerController::class, ['except' => 'show','create','edit']);

    Route::resource('settings', SettingController::class, ['except' => 'index','create','edit']);
    Route::resource('contact_us', ContactUsController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('complain_suggestions', ComplainSuggestionController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('welcomes', WelcomeController::class, ['except' => 'show','create','edit']);
    Route::resource('report_reasons', ReportReasonController::class, ['except' => 'show','create','edit']);

    Route::get('admins/status/{id}', [AdminController::class, 'changeStatus'])->name('admins.changeStatus');
    Route::delete('admins/history-log/{id}/delete', [AdminController::class, 'destroyHistoryLog'])->name('admins.destroyHistoryLog');
    Route::resource('admins', AdminController::class, ['except' => 'create','edit']);
    Route::get('admins/history/{id}', [AdminController::class,'loginHistory'])->name('admins.history');

    Route::post('users/notification/{id}', [UserController::class, 'sendNotification'])->name('users.sendNotification');
    Route::get('users/status/{id}', [UserController::class, 'changeStatus'])->name('users.changeStatus');
    Route::get('users/notification/status/{id}', [UserController::class, 'changeNotification'])->name('users.changeNotification');
    Route::resource('users', UserController::class, ['except' => 'show','create','edit']);

    Route::resource('companies', CompanyController::class, ['except' => 'create','edit']);
    Route::resource('commercial_advertisements', CommercialAdvertisementsController::class, ['except' => 'create','edit']);
    Route::get('commercial_advertisements/status/{id}', [CommercialAdvertisementsController::class, 'changeStatus'])->name('commercial_advertisements.changeStatus');
    Route::resource('notifications', NotificationController::class, ['except' => 'show','create','update','edit']);

    Route::resource('profile', ProfileController::class, ['except' => 'show','create','update','edit']);

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('set-locale/{locale}', function ($locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Categories\StoreCategoryRequest;
use App\Http\Requests\Admin\Categories\UpdateCategoryRequest;
use App\Imports\CategoriesImport;
use App\Models\AdvertisementType;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

class CategoryController extends Controller
{
    public function index()
    {
        $this->authorize('viewAny', Category::class);

        return view('admin.categories.index');
    }

    public function show(Category $category)
    {
        $this->authorize('view', Category::class);

        return view('admin.categories.show', compact('category'));
    }

    public function store(StoreCategoryRequest $request)
    {
        $this->authorize('create', Category::class);

        Category::create([
            'name'          => $request->name,
            'parent_id'     => $request->parent_id,
            'title_name'    => $request->title_name,
            'is_company'    => $request->is_company ? 1 : 0,
            'image'         => $request->image,
            'language'      => 'ar',
        ]);

        return back()->with('success', __('The action ran successfully!'));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $this->authorize('update', Category::class);

        $category->update([
            'name'          => $request->edit_name,
            'title_name'    => $request->edit_title_name,
            'order'         => $request->order,
            'is_company'    => $request->edit_is_company ? 1 : 0,
        ]);

        if ($request->hasFile('edit_image')) {
            $category->update([ 'image' => $request->edit_image ]);

            if(!empty($category->image)) {
                Storage::delete($category->image);
            }
        }
        if (!$request->hasFile('edit_image')) {


            if(!empty($category->image)) {
                Storage::delete($category->image);
            }
            $category->update(['image' => null]);

        }


        return back()->with('success', __('The action ran successfully!'));
    }

    public function destroy(Category $category)
    {
        $this->authorize('delete', Category::class);

        Storage::delete($category->image);

        $category->delete();

        return back()->with('success', __('The action ran successfully!'));
    }

    public function excel(Request $request)
    {
        Excel::import(new CategoriesImport, $request->file);

        return back()->with('success', __('The action ran successfully!'));
    }

    public function changeStatus($categoryId)
    {
        $status = request()->status == "true" ? 1 : 0;

        Category::find($categoryId)->update([ 'active' => $status ]);
    }

//    public function destroyAll(Request $request)
//    {
//        dd($request->all());
//    }
    public function getAdvertisementsTypes(Request $request){
        $category=Category::whereId($request->category_id)->first();
        $tags= $category->types;
        return view('admin.categories.properties.types', compact('tags'));

    }
    public function addAdvertisementsTypes(Request $request){
        AdvertisementType::create([
            'name'=>$request->name,
            'category_id'=>$request->category_id
        ]);
        return back()->with('success', __('The action ran successfully!'));

    }
    public function updateAdvertisementsTypes(Request $request,$id){
        $tag=AdvertisementType::whereId($id)->first();
        $tag->update([
            'name'=>$request->name,

        ]);
        return back()->with('success', __('The action ran successfully!'));

    }
    public function deleteAdvertisementsTypes($id){
        $this->authorize('delete', Category::class);

        $tag=AdvertisementType::whereId($id)->first();
        $tag->delete();

        return back()->with('success', __('The action ran successfully!'));

    }

}

app/Http/Controllers/Admin/PropertiesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Imports\ProperitiesImport;
use App\Models\AttributeCategory;
use App\Models\Category;
use App\Models\Property;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

class PropertiesController extends Controller
{
    public function index(Request $request)
    {
        $this->authorize('viewAny', Category::class);

        $sub_categories = Category::find($request->category_id)->subcategory()->pluck('id');

//        $attributes =
//        AttributeCategory::where('category_id', $request->category_id)
//        ->orWhereIn('sub_category_id', $sub_categories)
//        ->with('translation')
//        ->get();
        $attributes = Property::whereHas('categories', function ($query) use ($sub_categories,$request) {
            $query->whereIn('category_id', $sub_categories)->orWhere('category_id',$request->category_id);
        })
            ->get();


        return view('admin.categories.properties.index', compact('attributes'));
    }

    public function show($id)
    {
        $this->authorize('viewAny', Category::class);

//        $attributes =
//            AttributeCategory::where('parent_id', $id)
//                ->with('parent', 'translation')
//                ->get();
        $attributes =
            Property::where('parent_id', $id)
                ->with('parent')
                ->get();

//        $category_id = Property::findOrFail($id)->category_id;
//        $category_id = 5;

        return view('admin.categories.properties.show', compact('attributes', 'id'));
    }

    public function store(Request $request)
    {
        $this->authorize('create', Category::class);
//        dd($request->all());

        if ($request->name) {
//            $attribute = AttributeCategory::create([
//                'category_id' => $request->category_id,
//                'key' => $request->key_ar,
//                'value_type' => $request->value_type,
//                'language' => 'ar'
//            ]);
//
//            $attribute->translation()->updateOrCreate([
//                'key' => $request->key_en,
//                'language' => 'en'
//            ]);
            $attribute = Property::create([
//                'category_id' => $request->category_id,
                'name' => $request->name,
                'type' => $request->value_type,
                'property_type' => $request->property_type,
                'image'                     => $request->image,

                'language' => 'ar'
            ]);

//            $attribute->translation()->updateOrCreate([
//                'name' => $request->key_en,
//                'language' => 'en'
//            ]);
            $attribute->categories()->attach($request->category_id);
//            dd($attribute);
        }

        if ($request->value_ar) {
            $value = Property::create([
                'parent_id' => $request->parent_id,
                'name' => $request->value_ar,
                'image' => $request->image,

                'language' => 'ar'
            ]);

//            $value->translation()->updateOrCreate([
//                'name' => $request->value_en,
//                'language' => 'en'
//            ]);
        }


        return back()->with('success', __('The action ran successfully!'));
    }

    public function update(Request $request, $id)
    {
        $this->authorize('update', Category::class);

        $attributeCategory = Property::findOrFail($id);
        if ($request->edit_value_ar) {
            $attributeCategory->update([
                'name' => $request->edit_value_ar,
                'type' => $request->edit_value_type,
                'property_type' => $request->property_type,
            ]);

            if ($request->edit_value_type == 'text') {
                $attributeCategory->values()->delete();
            }
            if($request->edit_image) {
                $attributeCategory->update([
                    'image' => $request->edit_image
                ]);
            }


//            $attributeCategory->translation()->updateOrCreate(
//                [
//                    'translation_id' => $attributeCategory->id,
//                    'language' => 'en'
//                ],
//                [
//                    'name' => $request->edit_key_en,
//                    'language' => 'en'
//                ]
//            );
        }

        if ($request->edit_value_ar) {
            $attributeCategory->update([
                'name' => $request->edit_value_ar,
            ]);

//            $attributeCategory->translation()->updateOrCreate(
//                [
//                    'translation_id' => $attributeCategory->id,
//                    'language' => 'en'
//                ],
//                [
////                    'value' => $request->edit_value_en,
//                    'name' => $request->edit_value_text_en,
//                    'language' => 'en'
//                ]
//            );
        }

        return back()->with('success', __('The action ran successfully!'));
    }

    public function destroy($id)
    {
        $this->authorize('delete', Category::class);

        $attributeCategory = Property::findOrFail($id);

        if ($attributeCategory->advertisements()->count()) {
            return back()->with('error', 'Attributes cannot be deleted because of related ads');
        }
//        $attributeCategory->translation()->delete();

        $attributeCategory->delete();


        if ($attributeCategory->values()->count()) {
            $attributeCategory->values()->delete();
        }

        return back()->with('success', __('The action ran successfully!'));
    }
    public function excel(Request $request)
    {
        Excel::import(new ProperitiesImport(), $request->file);

        return back()->with('success', __('The action ran successfully!'));
    }

}

resources/views/admin/categories/properties/index.blade.php
@extends('layouts.admin', ['title' => __('Fields')])
@section('css')
    <!-- datatable style -->
    @include('admin.includes.datatable.style')
@endsection
@section('breadcrumb')
    <h3>{{__('Fields')}}</h3>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard.index')}}"><i data-feather="home"></i></a></li>
        <li class="breadcrumb-item active">{{__('Fields')}}</li>
    </ol>
@endsection
@section('button')
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createModal">
        <i class="fa fa-plus"></i>
        {{__('Add')}}
    </button>
    <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#excelModal">
        <i class="fa fa-file-excel-o"></i>
        {{__('Attributes excel')}}
    </button>

@endsection
@section('content')

    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="datatable">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>

                            <th scope="col">{{ __('Name') }}</th>
                            <th scope="col">{{ __('Attributes type') }}</th>
                            <th scope="col">{{ __('Fields type') }}</th>
                            <th scope="col">{{ __('Image') }}</th>
                            <th scope="col">{{ __('Action') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($attributes as $key => $attribute)
                        <tr>
                            <th scope="row">{{ $key + 1 }}</th>

                            <td>{{ $attribute->name }}</td>
                            <td>{{ __($attribute->property_type) }}</td>
                            <td>{{ __($attribute->type) }}</td>
                            <td> <img src="{{ $attribute->image }}" width="70px"></td>
                            <td>
                                @if($attribute->type!='text' && $attribute->type!='switch')
                                <a href='{{route('admin.property_fields.show', $attribute->id)}}' title='{{__('View')}}' class='btn btn-primary btn-sm btn-condensed'>
                                    <i class="fa fa-eye"></i> {{__('View')}}
                                </a>
                                @endif
                                <button class='btn btn-warning btn-sm btn-condensed' onclick='openModalEdit({{$attribute}})' >
                                    <i class="fa fa-edit"></i> {{__('Edit')}}
                                </button>
                                <button class='btn btn-danger btn-sm btn-condensed' onclick='openModalDelete({{$attribute->id}})' >
                                    <i class="fa fa-trash"></i> {{__('Delete')}}
                                </button>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Start create category_fields -->
    @component('admin.includes.modal')
        @slot('modalID')
            createModal
        @endslot
        @slot('modalFormId')
            form_id
        @endslot
        @slot('modalTitle')
            {{__('Add')}}
        @endslot
        @slot('modalRoute')
            {{route('admin.property_fields.store')}}
        @endslot
        @slot('modalContent')
            <div class="row">
                <input type="hidden" name="category_id" value="{{request()->category_id}}">

                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Name')}} <span style="color:red">*</span></label>
                    <input type="text" name="name" class="form-control" value="{{old('name')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'name'])
                </div>


                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="key_type">{{__('Type')}} <span style="color:red">*</span></label>
                    <select class="form-control" name="value_type">
                        <option disabled selected>{{__('Select Action')}}</option>
                        <option value="radio">{{__('radio')}}</option>
                        <option value="switch">{{__('switch')}}</option>
                        <option value="horizontal_view">{{__('horizontal view')}}</option>
                        <option value="text">{{__('text')}}</option>
                        <option value="integer">{{__('integer')}}</option>
                    </select>
                    @include('admin.includes.alerts.error', ['input' => 'value_type'])
                </div>
                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="key_type">{{__('Property Type')}} <span style="color:red">*</span></label>
                    <select class="form-control" name="property_type">
                        <option disabled selected>{{__('Select Action')}}</option>
                        <option value="specification">{{__('Specifications')}}</option>
                        <option value="feature">{{__('Features')}}</option>
                    </select>
                    @include('admin.includes.alerts.error', ['input' => 'property_type'])
                </div>
                <div class="col-sm-12 mt-4">
                    <label class="text-muted font-14">{{__('Image')}} </label>
                    <input type="file" name="image" class="dropify" data-max-file-size="40M"/>
                    @include('admin.includes.alerts.error', ['input' => 'image'])
                </div>

            </div>
        @endslot
    @endcomponent
    <!-- End create category_fields -->

    <!-- Start edit category_fields -->
    @component('admin.includes.modal')
        @slot('modalID')
            editModal
        @endslot
        @slot('modalFormId')
            edit_form_id
        @endslot
        @slot('modalTitle')
            {{__('Edit')}}
        @endslot
        @slot('modalMethodPutOrDelete')
            @method('put')
        @endslot
        @slot('modalContent')
            <div class="row">
                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Name')}} </label>
                    <input type="text" id="e_key_ar" name="name" class="form-control" required>
                    @include('admin.includes.alerts.error', ['input' => 'name'])
                </div>


                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="key_type">{{__('Type')}}</label>
                    <select class="form-control" name="edit_value_type" id="e_value_type">
                        <option disabled selected>{{__('Select Action')}}</option>
                        <option value="radio">{{__('radio')}}</option>
                        <option value="switch">{{__('switch')}}</option>
                        <option value="horizontal_view">{{__('horizontal view')}}</option>
                        <option value="text">{{__('text')}}</option>
                        <option value="integer">{{__('integer')}}</option>

                    </select>

                    @include('admin.includes.alerts.error', ['input' => 'edit_value_type'])
                </div>
                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="key_type">{{__('Property Type')}} <span style="color:red">*</span></label>
                    <select id="property_type_edit" class="form-control" name="property_type">
                        <option disabled selected>{{__('Select Action')}}</option>
                        <option value="specification">{{__('Specifications')}}</option>
                        <option value="feature">{{__('Features')}}</option>
                    </select>
                    @include('admin.includes.alerts.error', ['input' => 'property_type'])
                </div>
                <div class="col-sm-12 mt-4">
                    <label class="text-muted font-14">{{__('Image')}}</label>
                    <input type="file" id="e_image" name="edit_image"/>
                    @include('admin.includes.alerts.error', ['input' => 'edit_image'])
                </div>

            </div>

        @endslot
    @endcomponent
    <!-- End edit category_fields -->
    @component('admin.includes.modal')
        @slot('modalID')
            excelModal
        @endslot
        @slot('modalTitle')
            {{__('Attributes excel')}}
        @endslot
        @slot('modalRoute')
            {{route('admin.category_fields.excel')}}
        @endslot
        @slot('modalContent')
            <div class="row">
                <input type="hidden" name="category_id" value="{{request()->category_id}}">

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="file">{{__('File')}}</label>
                    <input type="file" id="file" name="file"/>
                    @include('admin.includes.alerts.error', ['input' => 'file'])
                </div>
            </div>

        @endslot
    @endcomponent

    <!-- Start delete category_fields -->
    @component('admin.includes.modal')
        @slot('modalID')
            deleteModal
        @endslot
        @slot('modalFormId')
            delete_form_id
        @endslot
        @slot('modalTitle')
            {{__('Delete')}}
        @endslot
        @slot('modalMethodPutOrDelete')
            @method('delete')
        @endslot
        @slot('modalContent')
            <div class="text-center">
                <span class="text-danger font-16">
                    {{__('Are you sure you want to run this action?')}}
                </span>
            </div>
        @endslot
    @endcomponent
    <!-- End delete category_fields -->

@endsection

@section('script')
    @include('admin.includes.alerts.message')
    <!-- datatable scripts -->
    @include('admin.includes.datatable.scripts')
{{--    <script src="/admin_main/js/ajax-normal-file.js"></script>--}}

    <script>
        function openModalEdit(attribute)
        {
            console.log(attribute);
            $('#e_key_ar').val(attribute.name);
            $("#e_value_type option[value ='"+attribute.type+"' ]").prop('selected', true);
            $("#property_type_edit option[value ='"+attribute.property_type+"' ]").prop('selected', true);

            // $('#e_value_type').val(attribute.value_type);

            $('.action_form').attr('action', '{{route('admin.property_fields.update', '')}}' + '/' + attribute.id);
            $('#editModal').modal('show');
        }

        $('#editModal').on('hide.bs.modal', function() {
            $('.action_form').attr('action', '{{route('admin.property_fields.store')}}');
        })

        function openModalDelete(category_fields_id)
        {
            $('.action_form').attr('action', '{{route('admin.property_fields.destroy', '')}}' + '/' + category_fields_id);
            $('#deleteModal').modal('show');
        }

        $('#deleteModal').on('hide.bs.modal', function() {
            $('.action_form').attr('action', '{{route('admin.property_fields.store')}}');
        })
    </script>
@endsection