routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeCategoryController;
use App\Http\Controllers\Admin\AdvertisementController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\GovernorateController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\AreaController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\WelcomeController;
use App\Http\Controllers\Admin\ReportReasonController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\ComplainSuggestionController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\PropertiesController;
use App\Http\Controllers\Admin\CommercialAdvertisementsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){ return redirect()->route('admin.login'); });

Route::get('login', [AuthController::class, 'viewLoginPage'])->name('login');
Route::post('login', [AuthController::class, 'authenticate'])->name('authenticate');

Route::middleware('auth')->group(function (){
    Route::get('dashboard', [HomeController::class, 'reportStatistics'])->name('dashboard.index');

//    Route::post('categories/delete', [CategoryController::class, 'destroyAll'])->name('categories.destroyAll');
    Route::get('categories/status/{id}', [CategoryController::class, 'changeStatus'])->name('categories.changeStatus');
    Route::post('categories/excel', [CategoryController::class, 'excel'])->name('categories.excel');
    Route::resource('categories', CategoryController::class, ['except' => 'create','edit']);
    Route::post('category_fields/excel', [AttributeCategoryController::class, 'excel'])->name('category_fields.excel');
    Route::resource('category_fields', AttributeCategoryController::class, ['except' => 'create','edit']);
    Route::get('get-advertisement-types', [CategoryController::class, 'getAdvertisementsTypes'])->name('categories.get-advertisement-types');
    Route::post('get-advertisement-types', [CategoryController::class, 'addAdvertisementsTypes'])->name('categories.add-advertisement-types');
    Route::put('update-advertisement-types/{id}', [CategoryController::class, 'updateAdvertisementsTypes'])->name('categories.update-advertisement-types');
    Route::delete('delete-advertisement-types/{id}', [CategoryController::class, 'deleteAdvertisementsTypes'])->name('categories.delete-advertisement-types');

    Route::get('packages/status/{id}', [PackagesController::class, 'changeStatus'])->name('packages.changeStatus');
    Route::resource('packages', PackagesController::class, ['except' => 'create','edit']);
    Route::resource('property_fields', PropertiesController::class, ['except' => 'create', 'edit']);
    Route::post('property_fields/excel', [PropertiesController::class, 'excel'])->name('property_fields.excel');

    Route::get('advertisements/delete_image/{id}', [AdvertisementController::class, 'deleteImage'])->name('advertisements.deleteImage');
    Route::resource('advertisements', AdvertisementController::class, ['except' => 'show', 'store','create','edit']);

    Route::get('advertisements/reports/{advertisement}', [AdvertisementController::class, 'reportedAdvertisementsUpdate'])->name('advertisements.reports.update');
    Route::delete('advertisements/reports/destroy/{id}', [AdvertisementController::class, 'destroyReportedAdvertisements'])->name('advertisements.reports.destroy');

    Route::resource('comments', CommentController::class, ['except' => 'show', 'store','create','edit']);

    Route::resource('countries', CountryController::class, ['except' => 'show','create','edit']);
    Route::resource('governorates', GovernorateController::class, ['except' => 'show','create','edit']);
    Route::resource('cities', CityController::class, ['except' => 'show','create','edit']);
    Route::resource('areas', AreaController::class, ['except' => 'show','create','edit']);

    Route::resource('banners', BannerController::class, ['except' => 'show','create','edit']);

    Route::resource('settings', SettingController::class, ['except' => 'index','create','edit']);
    Route::resource('contact_us', ContactUsController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('complain_suggestions', ComplainSuggestionController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('welcomes', WelcomeController::class, ['except' => 'show','create','edit']);
    Route::resource('report_reasons', ReportReasonController::class, ['except' => 'show','create','edit']);

    Route::get('admins/status/{id}', [AdminController::class, 'changeStatus'])->name('admins.changeStatus');
    Route::delete('admins/history-log/{id}/delete', [AdminController::class, 'destroyHistoryLog'])->name('admins.destroyHistoryLog');
    Route::resource('admins', AdminController::class, ['except' => 'create','edit']);
    Route::get('admins/history/{id}', [AdminController::class,'loginHistory'])->name('admins.history');

    Route::post('users/notification/{id}', [UserController::class, 'sendNotification'])->name('users.sendNotification');
    Route::get('users/status/{id}', [UserController::class, 'changeStatus'])->name('users.changeStatus');
    Route::get('users/notification/status/{id}', [UserController::class, 'changeNotification'])->name('users.changeNotification');
    Route::resource('users', UserController::class, ['except' => 'show','create','edit']);

    Route::resource('companies', CompanyController::class, ['except' => 'create','edit']);
    Route::resource('commercial_advertisements', CommercialAdvertisementsController::class, ['except' => 'create','edit']);
    Route::get('commercial_advertisements/status/{id}', [CommercialAdvertisementsController::class, 'changeStatus'])->name('commercial_advertisements.changeStatus');
    Route::resource('notifications', NotificationController::class, ['except' => 'show','create','update','edit']);

    Route::resource('profile', ProfileController::class, ['except' => 'show','create','update','edit']);

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('set-locale/{locale}', function ($locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Categories\StoreCategoryRequest;
use App\Http\Requests\Admin\Categories\UpdateCategoryRequest;
use App\Imports\CategoriesImport;
use App\Models\AdvertisementType;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

class CategoryController extends Controller
{
    public function index()
    {
        $this->authorize('viewAny', Category::class);

        return view('admin.categories.index');
    }

    public function show(Category $category)
    {
        $this->authorize('view', Category::class);

        return view('admin.categories.show', compact('category'));
    }

    public function store(StoreCategoryRequest $request)
    {
        $this->authorize('create', Category::class);

        Category::create([
            'name'          => $request->name,
            'parent_id'     => $request->parent_id,
            'title_name'    => $request->title_name,
            'is_company'    => $request->is_company ? 1 : 0,
            'image'         => $request->image,
            'language'      => 'ar',
        ]);

        return back()->with('success', __('The action ran successfully!'));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $this->authorize('update', Category::class);

        $category->update([
            'name'          => $request->edit_name,
            'title_name'    => $request->edit_title_name,
            'order'         => $request->order,
            'is_company'    => $request->edit_is_company ? 1 : 0,
        ]);

        if ($request->hasFile('edit_image')) {
            $category->update([ 'image' => $request->edit_image ]);

            if(!empty($category->image)) {
                Storage::delete($category->image);
            }
        }
        if (!$request->hasFile('edit_image')) {


            if(!empty($category->image)) {
                Storage::delete($category->image);
            }
            $category->update(['image' => null]);

        }


        return back()->with('success', __('The action ran successfully!'));
    }

    public function destroy(Category $category)
    {
        $this->authorize('delete', Category::class);

        Storage::delete($category->image);

        $category->delete();

        return back()->with('success', __('The action ran successfully!'));
    }

    public function excel(Request $request)
    {
        Excel::import(new CategoriesImport, $request->file);

        return back()->with('success', __('The action ran successfully!'));
    }

    public function changeStatus($categoryId)
    {
        $status = request()->status == "true" ? 1 : 0;

        Category::find($categoryId)->update([ 'active' => $status ]);
    }

//    public function destroyAll(Request $request)
//    {
//        dd($request->all());
//    }
    public function getAdvertisementsTypes(Request $request){
        $category=Category::whereId($request->category_id)->first();
        $tags= $category->types;
        return view('admin.categories.properties.types', compact('tags'));

    }
    public function addAdvertisementsTypes(Request $request){
        AdvertisementType::create([
            'name'=>$request->name,
            'category_id'=>$request->category_id
        ]);
        return back()->with('success', __('The action ran successfully!'));

    }
    public function updateAdvertisementsTypes(Request $request,$id){
        $tag=AdvertisementType::whereId($id)->first();
        $tag->update([
            'name'=>$request->name,

        ]);
        return back()->with('success', __('The action ran successfully!'));

    }
    public function deleteAdvertisementsTypes($id){
        $this->authorize('delete', Category::class);

        $tag=AdvertisementType::whereId($id)->first();
        $tag->delete();

        return back()->with('success', __('The action ran successfully!'));

    }

}

app/Http/Controllers/Api/V100/Categories/GetAdvertisementTypes.php
<?php

namespace App\Http\Controllers\Api\V100\Categories;

use App\Http\Controllers\Controller;
use App\Models\AdvertisementType;
use App\Services\RespondActive;
use \App\Http\Requests\Api\V100\Categories\GetAdvertisementTypes as GetAdvertisementTypesRequest;
class GetAdvertisementTypes extends Controller
{
    public function __invoke(GetAdvertisementTypesRequest $request)
    {
        $types=AdvertisementType::where('category_id',$request->category_id)->select('id','name as key_name')->get();



        return RespondActive::success('The action ran successfully!', $types);
    }

}

app/Http/Controllers/Api/V100/Categories/GetAttributesCategory.php
<?php

namespace App\Http\Controllers\Api\V100\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V100\Categories\GetAttributesCategoryRequest;
use App\Http\Resources\Categories\AttributesCategoryResource;
use App\Models\AttributeCategory;
use App\Models\Category;
use App\Services\RespondActive;

class GetAttributesCategory extends Controller
{
    public function __invoke(GetAttributesCategoryRequest $request)
    {
//        $attributes =
//        AttributeCategory::where('category_id', $request->category_id)
//        ->with('values')
//        ->get();
        $category=Category::whereId($request->category_id)->first();

            $attributes=$category->properties()->with('values')->get();

        $attributes = AttributesCategoryResource::collection($attributes);



        return RespondActive::success('The action ran successfully!', $attributes);
    }
}

app/Http/Controllers/Api/V100/Categories/GetCategories.php
<?php

namespace App\Http\Controllers\Api\V100\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V100\Categories\GetCategoryRequest;
use App\Http\Resources\Categories\CategoriesResource;
use App\Models\Category;
use App\Services\RespondActive;

class GetCategories extends Controller
{
    public function __invoke(GetCategoryRequest $request)
    {
        switch($request->company){
            case 0:
                if($request->filter) {
                    $categories =
                        Category::mainCategory()
                            ->where('id', '!=', 1)
                            ->orderBy('is_company', 'asc')
                            ->get();
                }else{
                    $categories =
                        Category::mainCategory()
                            ->where('id', '!=', 1)
                            ->where('is_company', 0)
                            ->get();

                }
                break;
            case 1:
                $categories = Category::whereNotNull('parent_id')->where('is_company', 1)->get();
                break;
        }

        // if (optional(auth('sanctum')->user())->account_type == 'company') {
        //     $categories = Category::whereNull('translation_id')->where('is_company', 1)->get();
        // }

        $categories = CategoriesResource::collection($categories);

        return RespondActive::success('The action ran successfully!', $categories);
    }
}

app/Http/Controllers/Api/V100/Categories/GetSubCategory.php
<?php

namespace App\Http\Controllers\Api\V100\Categories;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V100\Categories\GetSubCategoryRequest;
use App\Http\Resources\Categories\SubCategoryResource;
use App\Http\Resources\Categories\ValuesAttributeCategoryResource;
use App\Models\Category;
use App\Services\RespondActive;

class GetSubCategory extends Controller
{
    public function __invoke(GetSubCategoryRequest $request)
    {
        $categories = Category::where('parent_id', $request->category_id)->active()->get();

        $data['title'] = Category::find($request->category_id)->title_name;

        $data['sub_categories'] = SubCategoryResource::collection($categories);

        return RespondActive::success('The action ran successfully!', $data);
    }
}

resources/views/admin/categories/index.blade.php
@extends('layouts.admin', ['title' => __('Categories')])
@section('css')
    <!-- datatable style -->
    @include('admin.includes.datatable.style')

    <!-- dropify -->
    <link href="/admin_main/libs/dropify/dropify.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('breadcrumb')
    <h3>{{__('Categories')}}</h3>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard.index')}}"><i data-feather="home"></i></a></li>
        <li class="breadcrumb-item active">{{__('Categories')}}</li>
    </ol>
@endsection
@section('button')
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createModal">
        <i class="fa fa-plus"></i>
        {{__('Add')}}
    </button>
@endsection
@section('content')

    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="datatable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>{{__('Image')}}</th>
                            <th>{{__('Name')}}</th>
                            <th>{{__('Order')}}</th>
                            <th>{{__('Title sub category')}}</th>
                            <th>{{(__('Status'))}}</th>
                            <th>{{__('Actions')}}</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Start create category -->
    @component('admin.includes.modal')
        @slot('modalID')
            createModal
        @endslot
        @slot('modalTitle')
            {{__('Add')}}
        @endslot
        @slot('modalRoute')
            {{route('admin.categories.store')}}
        @endslot
        @slot('modalContent')
            <div class="row">
                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Name')}} <span style="color:red">*</span></label>
                    <input type="text" name="name" class="form-control" value="{{old('name')}}" placeholder="{{__('Name')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'name'])
                </div>

                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Title')}} <span style="color:red">*</span></label>
                    <input type="text" name="title_name" class="form-control" value="{{old('title_name')}}" placeholder="{{__('Title sub category')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'title_name'])
                </div>

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="is_company">{{__('Is company')}}</label>
                    <input type="checkbox" id="is_company" name="is_company" class="check">
                    @include('admin.includes.alerts.error', ['input' => 'is_company'])
                </div>

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="image">{{__('Image')}} {{__('Width')}} 174 px  * {{__('Height')}} 131 px<span style="color:red">*</span></label>
                    <input type="file" id="image" name="image" class="dropify" data-max-file-size="40M"/>
                    @include('admin.includes.alerts.error', ['input' => 'image'])
                </div>
            </div>

        @endslot
    @endcomponent
    <!-- End create category -->

    <!-- Start edit category -->
    @component('admin.includes.modal')
        @slot('modalID')
            editModal
        @endslot
        @slot('modalTitle')
            {{__('Edit')}}
        @endslot
        @slot('modalMethodPutOrDelete')
            @method('put')
        @endslot
        @slot('modalContent')
            <div class="row">
                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Name')}}</label>
                    <input type="text" id="e_name" name="edit_name" class="form-control" placeholder="{{__('Name arabic')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'edit_name'])
                </div>

                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Title')}} </label>
                    <input type="text" id="e_title_name" name="edit_title_name" class="form-control" placeholder="{{__('Title sub category')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'edit_title_name'])
                </div>

                <div class="col-sm-12">
                    <label class="text-muted font-14">{{__('Order')}} </label>
                    <input type="number" id="e_order" name="order" class="form-control" placeholder="{{__('Order')}}" required>
                    @include('admin.includes.alerts.error', ['input' => 'order'])
                </div>

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="e_is_company">{{__('Is company')}}</label>
                    <input type="checkbox" id="e_is_company" name="edit_is_company" class="check">
                    @include('admin.includes.alerts.error', ['input' => 'edit_is_company'])
                </div>

                <div class="col-sm-12 mt-2">
                    <label class="text-muted font-14" for="image" id="sizeLabel">{{__('Image')}} {{__('Width')}}  174 px  * {{__('Height')}} 131 px</label>
                    <input type="file" id="e_image" name="edit_image" data-max-file-size="40M"/>
                    @include('admin.includes.alerts.error', ['input' => 'edit_image'])
                </div>

            </div><!-- row -->
        @endslot
    @endcomponent
    <!-- End edit category -->

    <!-- Start delete category -->
    @component('admin.includes.modal')
        @slot('modalID')
            deleteModal
        @endslot
        @slot('modalTitle')
            {{__('Delete')}}
        @endslot
        @slot('modalMethodPutOrDelete')
            @method('delete')
        @endslot
        @slot('modalContent')
            <div class="text-center">
                <span class="text-danger font-16">
                    {{__('Are you sure you want to run this action?')}}
                </span>
            </div>
        @endslot
    @endcomponent
    <!-- End delete category -->
@endsection

@section('script')
    @include('admin.includes.alerts.message')
    <!-- datatable scripts -->
    @include('admin.includes.datatable.scripts')

    <!-- dropify js -->
    <script src="/admin_main/libs/dropify/dropify.min.js"></script>

    <!-- form-upload init -->
    <script src="/admin_main/js/form-fileupload.init.js"></script>
    <script>
        $(document).ready(function() {
            $("#datatable").DataTable({
                stateSave: true,
                "responsive": true, "lengthChange": false, "autoWidth": true,
                "processing": true, "serverSide": true, "order": [ [0, 'desc'] ],
                "ajax": {
                    url: "/api/datatable/categories",
                    "dataSrc": "data.data",
                    "data" : {'parent_id': '{{isset($category->id) ? $category->id : NULL}}' },
                },
                language: {
                    url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Arabic.json',
                },
                "columns": [
                    { data: 'id' },
                    { data: "image", render: function (data, type, row)
                        { return '<img src="'+row.image+'" style="width: 70px">' }
                    },
                    { data: 'name' },
                    { data: 'order' },
                    { data: 'title_name' },
                    { data: "status", render: function (data, type, row)
                        {
                            if(row.active === 1) {
                                return  '<label class="switch">'+
                                        '<input type="checkbox" id="switchValue'+row.id+'" checked="" onchange=changeStatus('+row.id+')>' +
                                        '<span class="switch-state"></span>'+
                                        '</label>'
                            } else {
                                return  '<label class="switch">'+
                                        '<input type="checkbox" id="switchValue'+row.id+'" onchange=changeStatus('+row.id+')>' +
                                        '<span class="switch-state"></span>'+
                                        '</label>'
                            }
                        }
                    },
                    { data: "operations", render: function (data, type, row) {
                            return  " <a href='{{route('admin.categories.show', '')}}"+ '/' + row.id +" ' title='{{__('View')}}' class='btn btn-primary btn-sm btn-condensed a_button' >" +
                                    '<i class="fa fa-eye"></i>' +
                                    '</a> ' +
                                (row.is_company != 1 && !row.name.includes("VIP") && row.id!=1 && row.id!=3010?
                                    {{--"<a href='{{route('admin.category_fields.index')}}?category_id=" + row.id +"' title='{{__('Attributes')}}' class='btn btn-dark btn-sm btn-condensed a_button' >" +--}}
                                    {{--'<i class="fa fa-pencil"></i>' + '</a> '+--}}
                                    "<a href='{{route('admin.property_fields.index')}}?category_id=" + row.id +"' title='{{__('Attributes')}}' class='btn btn-dark btn-sm btn-condensed a_button' >" +
                                    '<i class="fa fa-pencil"></i>' + '</a> '                                    +
                                    "<a href='{{route('admin.categories.get-advertisement-types')}}?category_id=" + row.id +"' class='btn btn-dark btn-sm btn-condensed a_button' title='{{__('Advertisements Types')}}' >" +
                                    '<i class="fa fa-window-restore"></i> ' +
                                    '</a> '

                                    : "")
                                    +"<button title='{{__('Edit')}}' class='btn btn-warning btn-sm btn-condensed' onclick='openModalEdit("+JSON.stringify(row)+")' >" +
                                    '<i class="fa fa-edit"></i>' +
                                    '</button> ' +
                                    '<button title="{{__('Delete')}}" class="btn btn-danger btn-sm btn-condensed" onclick=openModalDelete('+row.id+') >' +
                                    '<i class="fa fa-trash"></i>' +
                                    '</button>'
                        }
                    },
                ],
            });
        });

        function openModalEdit(category)
        {
            $('#e_name').val(category.name);
            $('#e_title_name').val(category.title_name);
            $('#e_order').val(category.order);
            if(category.id==3010){
                $('#sizeLabel').text("{{__('Image')}} {{__('Width')}}  353 px  * {{__('Height')}} 131 px");
            }
            else{
                $('#sizeLabel').text("{{__('Image')}} {{__('Width')}}  174 px  * {{__('Height')}} 131 px");

            }

            category.is_company === 1 ?
                $('#e_is_company').prop('checked', true)
                :
                $('#e_is_company').prop('checked', false);

                let imagenUrl = category.image;
                let drEvent = $('#e_image').dropify(
                    {
                        defaultFile: imagenUrl
                    });
                drEvent = drEvent.data('dropify');
                drEvent.resetPreview();
                drEvent.clearElement();
                drEvent.settings.defaultFile = imagenUrl;
                drEvent.destroy();
                drEvent.init();

            $('.action_form').attr('action', '{{route('admin.categories.update', '')}}' + '/' + category.id);
            $('#editModal').modal('show');
        }

        $('#editModal').on('hide.bs.modal', function() {
            $('.action_form').attr('action', '{{route('admin.categories.store')}}');
        })

        function openModalDelete(category_id)
        {
            $('.action_form').attr('action', '{{route('admin.categories.destroy', '')}}' + '/' + category_id);
            $('#deleteModal').modal('show');
        }

        $('#deleteModal').on('hide.bs.modal', function() {
            $('.action_form').attr('action', '{{route('admin.categories.store')}}');
        })

        function changeStatus(categoryId)
        {
            var isChecked = document.getElementById("switchValue"+categoryId).checked;

            $.get( '{{route('admin.categories.changeStatus', '')}}' + '/' + categoryId,
                { 'status': isChecked },
                function( data ) {
                    $.notify({
                            message:'The action ran successfully!'
                        },
                        {
                            type:'success',
                            allow_dismiss:true,
                            timer:1000,
                            delay:1000 ,
                        });
                });
        }

    </script>
@endsection