routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AttributeCategoryController;
use App\Http\Controllers\Admin\AdvertisementController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\GovernorateController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\AreaController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\WelcomeController;
use App\Http\Controllers\Admin\ReportReasonController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\ComplainSuggestionController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\PropertiesController;
use App\Http\Controllers\Admin\CommercialAdvertisementsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){ return redirect()->route('admin.login'); });

Route::get('login', [AuthController::class, 'viewLoginPage'])->name('login');
Route::post('login', [AuthController::class, 'authenticate'])->name('authenticate');

Route::middleware('auth')->group(function (){
    Route::get('dashboard', [HomeController::class, 'reportStatistics'])->name('dashboard.index');

//    Route::post('categories/delete', [CategoryController::class, 'destroyAll'])->name('categories.destroyAll');
    Route::get('categories/status/{id}', [CategoryController::class, 'changeStatus'])->name('categories.changeStatus');
    Route::post('categories/excel', [CategoryController::class, 'excel'])->name('categories.excel');
    Route::resource('categories', CategoryController::class, ['except' => 'create','edit']);
    Route::post('category_fields/excel', [AttributeCategoryController::class, 'excel'])->name('category_fields.excel');
    Route::resource('category_fields', AttributeCategoryController::class, ['except' => 'create','edit']);
    Route::get('get-advertisement-types', [CategoryController::class, 'getAdvertisementsTypes'])->name('categories.get-advertisement-types');
    Route::post('get-advertisement-types', [CategoryController::class, 'addAdvertisementsTypes'])->name('categories.add-advertisement-types');
    Route::put('update-advertisement-types/{id}', [CategoryController::class, 'updateAdvertisementsTypes'])->name('categories.update-advertisement-types');
    Route::delete('delete-advertisement-types/{id}', [CategoryController::class, 'deleteAdvertisementsTypes'])->name('categories.delete-advertisement-types');

    Route::get('packages/status/{id}', [PackagesController::class, 'changeStatus'])->name('packages.changeStatus');
    Route::resource('packages', PackagesController::class, ['except' => 'create','edit']);
    Route::resource('property_fields', PropertiesController::class, ['except' => 'create', 'edit']);
    Route::post('property_fields/excel', [PropertiesController::class, 'excel'])->name('property_fields.excel');

    Route::get('advertisements/delete_image/{id}', [AdvertisementController::class, 'deleteImage'])->name('advertisements.deleteImage');
    Route::resource('advertisements', AdvertisementController::class, ['except' => 'show', 'store','create','edit']);

    Route::get('advertisements/reports/{advertisement}', [AdvertisementController::class, 'reportedAdvertisementsUpdate'])->name('advertisements.reports.update');
    Route::delete('advertisements/reports/destroy/{id}', [AdvertisementController::class, 'destroyReportedAdvertisements'])->name('advertisements.reports.destroy');

    Route::resource('comments', CommentController::class, ['except' => 'show', 'store','create','edit']);

    Route::resource('countries', CountryController::class, ['except' => 'show','create','edit']);
    Route::resource('governorates', GovernorateController::class, ['except' => 'show','create','edit']);
    Route::resource('cities', CityController::class, ['except' => 'show','create','edit']);
    Route::resource('areas', AreaController::class, ['except' => 'show','create','edit']);

    Route::resource('banners', BannerController::class, ['except' => 'show','create','edit']);

    Route::resource('settings', SettingController::class, ['except' => 'index','create','edit']);
    Route::resource('contact_us', ContactUsController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('complain_suggestions', ComplainSuggestionController::class, ['except' => 'store', 'update', 'create','edit']);
    Route::resource('welcomes', WelcomeController::class, ['except' => 'show','create','edit']);
    Route::resource('report_reasons', ReportReasonController::class, ['except' => 'show','create','edit']);

    Route::get('admins/status/{id}', [AdminController::class, 'changeStatus'])->name('admins.changeStatus');
    Route::delete('admins/history-log/{id}/delete', [AdminController::class, 'destroyHistoryLog'])->name('admins.destroyHistoryLog');
    Route::resource('admins', AdminController::class, ['except' => 'create','edit']);
    Route::get('admins/history/{id}', [AdminController::class,'loginHistory'])->name('admins.history');

    Route::post('users/notification/{id}', [UserController::class, 'sendNotification'])->name('users.sendNotification');
    Route::get('users/status/{id}', [UserController::class, 'changeStatus'])->name('users.changeStatus');
    Route::get('users/notification/status/{id}', [UserController::class, 'changeNotification'])->name('users.changeNotification');
    Route::resource('users', UserController::class, ['except' => 'show','create','edit']);

    Route::resource('companies', CompanyController::class, ['except' => 'create','edit']);
    Route::resource('commercial_advertisements', CommercialAdvertisementsController::class, ['except' => 'create','edit']);
    Route::get('commercial_advertisements/status/{id}', [CommercialAdvertisementsController::class, 'changeStatus'])->name('commercial_advertisements.changeStatus');
    Route::resource('notifications', NotificationController::class, ['except' => 'show','create','update','edit']);

    Route::resource('profile', ProfileController::class, ['except' => 'show','create','update','edit']);

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('set-locale/{locale}', function ($locale) {
        session()->put('locale', $locale);
        return redirect()->back();
    })->name('locale.setting');
});

resources/views/admin/includes/footer.blade.php
<!-- footer start-->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 footer-copyright">
                <p class="mb-0">Copyright {{now()}} © Tabe All rights reserved.</p>
            </div>
            <div class="col-md-6">
                <p class="pull-right mb-0">Hand crafted & made with<i class="fa fa-heart"></i></p>
            </div>
        </div>
    </div>
</footer>

resources/views/admin/includes/left_sidemenu.blade.php
<!-- Page Sidebar Start-->
<div class="page-sidebar light-sidebar">
    <div class="main-header-left d-none d-lg-block">
        <div class="logo-wrapper">
            <a href="{{route('admin.dashboard.index')}}" style="margin: auto">
                <img src="/admin_main/images/logo.png" style="height: 90px">
            </a>
        </div>
    </div>
    <div class="sidebar custom-scrollbar">
        <ul class="sidebar-menu">
            @can('viewAny', "Dashboard")
                <li>
                    <a class="sidebar-header" href="{{route('admin.dashboard.index')}}">
                        <i data-feather="home"></i>
                        <span> {{__('Dashboard')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\User::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.users.index')}}">
                        <i data-feather="users"></i>
                        <span> {{__('Users')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', 'Admin')
                <li>
                    <a class="sidebar-header" href="{{route('admin.admins.index')}}">
                        <i data-feather="lock"></i>
                        <span> {{__('Admins')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\Category::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.categories.index')}}">
                        <i data-feather="align-justify"></i>
                        <span> {{__('Categories')}} </span>
                    </a>
                </li>
            @endcan
            @can('viewAny', \App\Models\Package::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.packages.index')}}">
                        <i data-feather="align-justify"></i>
                        <span> {{__('Packages')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\Advertisement::class)
                <li><a class="sidebar-header" href="#" onclick="event.preventDefault()"><i data-feather="tv"></i>
                        <span>{{__('Advertisements')}}</span><i class="fa fa-angle-right pull-right"></i>
                    </a>
                    <ul class="sidebar-submenu">
                        <li><a href="{{route('admin.advertisements.index')}}">
                                <i class="fa fa-circle"></i><span>{{__('Advertisements')}}</span>
                            </a>
                        </li>
                        <li><a href="{{route('admin.comments.index')}}">
                                <i class="fa fa-circle"></i><span>{{__('Comments')}}</span>
                            </a>
                        </li>
                    </ul>
                </li>
            @endcan

            @can('viewAny', 'Company')
                <li>
                    <a class="sidebar-header" href="{{route('admin.companies.index')}}">
                        <i data-feather="align-justify"></i>
                        <span> {{__('Companies')}} </span>
                    </a>
                </li>
            @endcan
            @can('viewAny', \App\Models\CommercialAdvertisement::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.commercial_advertisements.index')}}">
                        <i data-feather="align-justify"></i>
                        <span> {{__('Commercial Advertisements')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\Banner::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.banners.index')}}">
                        <i data-feather="image"></i>
                        <span> {{__('Banners')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\Country::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.countries.index')}}">
                        <i data-feather="globe"></i>
                        <span> {{__('Countries')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\Notification::class)
                    <li>
                        <a class="sidebar-header" href="{{route('admin.notifications.index')}}">
                            <i data-feather="bell"></i>
                            <span> {{__('Notifications')}} </span>
                        </a>
                    </li>
            @endcan

            @can('viewAny', \App\Models\Welcome::class)
                <li>
                    <a class="sidebar-header" href="{{route('admin.welcomes.index')}}">
                        <i data-feather="layout"></i>
                        <span> {{__('Welcome pages')}} </span>
                    </a>
                </li>
            @endcan

            @can('viewAny', \App\Models\Setting::class)
                <li><a class="sidebar-header" href="#" onclick="event.preventDefault()"><i data-feather="settings"></i><span>{{__('Settings')}}</span><i class="fa fa-angle-right pull-right"></i></a>
                    <ul class="sidebar-submenu">
                        <li><a href="{{route('admin.settings.show', 'premium_cost')}}"><i class="fa fa-circle"></i><span>{{__('Ads Premium cost')}}</span></a></li>
                        <li><a href="{{route('admin.settings.show', 'advertisement_modify_time')}}"><i class="fa fa-circle"></i><span>{{__('Ads modify time')}}</span></a></li>
                        <li><a href="{{route('admin.settings.show', 'terms_condition')}}"><i class="fa fa-circle"></i><span>{{__('Terms & condition')}}</span></a></li>
                        <li><a href="{{route('admin.settings.show', 'privacy_policy')}}"><i class="fa fa-circle"></i><span>{{__('Privacy Policy')}}</span></a></li>
                        <li><a href="{{route('admin.settings.show', 'about_us')}}"><i class="fa fa-circle"></i><span>{{__('About us')}}</span></a></li>
                        <li><a href="{{route('admin.settings.show', 'help')}}"><i class="fa fa-circle"></i><span>{{__('Help')}}</span></a></li>
                        <li><a href="{{route('admin.report_reasons.index')}}"><i class="fa fa-circle"></i><span>{{__('Report reasons')}}</span></a></li>
                        <li><a href="{{route('admin.contact_us.index')}}"><i class="fa fa-circle"></i><span>{{__('Contact us')}}</span></a></li>
                        <li style="padding-bottom: 30px"><a href="{{route('admin.complain_suggestions.index')}}"><i class="fa fa-circle"></i><span>{{__('Complain suggestion')}}</span></a></li>
                    </ul>
                </li>
            @endcan

{{--            @can('viewAny', 'Report')--}}
{{--                <li><a class="sidebar-header" href="#" onclick="event.preventDefault()"><i data-feather="bar-chart"></i><span>{{__('Reports')}}</span><i class="fa fa-angle-right pull-right"></i></a>--}}
{{--                    <ul class="sidebar-submenu">--}}
{{--                        <li><a href="{{route('admin.reports.orders')}}"><i class="fa fa-circle"></i><span> {{__('admin.ordersSideBar')}}</a></li>--}}
{{--                        <li><a href="{{route('admin.reports.orders.finished')}}"><i class="fa fa-circle"></i><span> {{__('admin.deliveredOrdersSideBar')}}</span></a></li>--}}
{{--                        <li><a href="{{route('admin.reports.products')}}"><i class="fa fa-circle"></i><span> {{__('admin.productsHistorySideBar')}}</span></a></li>--}}
{{--                        <li><a href="{{route('admin.reports.products.receipt')}}"><i class="fa fa-circle"></i><span> {{__('admin.productsReceiptSideBar')}}</span></a></li>--}}
{{--                        <li><a href="{{route('admin.reports.delegates')}}"><i class="fa fa-circle"></i><span> {{__('admin.delegatesSideBar')}}</span></a></li>--}}
{{--                        <li><a href="{{route('admin.reports.customers')}}"><i class="fa fa-circle"></i><span> {{__('admin.customersSideBar')}}</span></a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}
{{--            @endcan--}}

        </ul>

        <div style="text-align:center;">
            <a href="https://2grand.net/" target="_blank">
                <img src="/admin_main/images/Logo-Grand.png" style="width: 75px">
            </a>
        </div>
    </div>
</div>
<!-- Page Sidebar Ends-->

resources/views/admin/includes/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="{{$modalID}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form class="modal-content action_form" method="post" action="{{ isset($modalRoute) ? $modalRoute : '' }}" enctype="multipart/form-data">
            @csrf
            {{ isset($modalMethodPutOrDelete) ? $modalMethodPutOrDelete : ''}}
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{$modalTitle}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{$modalContent}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark btn-sm" data-dismiss="modal">{{__('Close')}} <i class="fa fa-times"></i></button>
               @if(!isset($modalHistory))
                <button type="submit" class="btn btn-primary btn-sm">{{__('Save')}} <i class="fa fa-check"></i></button>
               @endif
            </div>
        </form>
    </div>
</div>

resources/views/admin/includes/topbar.blade.php
<!-- Page Header Start-->
<div class="page-main-header" style="background-color: #4B2B6E">
    <div class="main-header-right row">
        <div class="main-header-left d-lg-none">
            <div class="logo-wrapper">
                <a href="{{route('admin.dashboard.index')}}" style="height: 95px">
                    <img src="/admin_main/images/logo.png" alt="">
                </a>
            </div>
        </div>
        <div class="mobile-sidebar d-block">
            <div class="media-body text-right switch-sm">
                <label class="switch"><a href="#"><i id="sidebar-toggle" data-feather="align-left"></i></a></label>
            </div>
        </div>
        <div class="nav-right col p-0">
            <ul class="nav-menus">
                <li>
{{--                    <form class="form-inline search-form" action="#" method="get">--}}
{{--                        <div class="form-group">--}}
{{--                            <div class="Typeahead Typeahead--twitterUsers">--}}
{{--                                <div class="u-posRelative">--}}
{{--                                    <input class="Typeahead-input form-control-plaintext" id="demo-input" type="text" name="q" placeholder="Search...">--}}
{{--                                    <div class="spinner-border Typeahead-spinner" role="status"><span class="sr-only">Loading...</span></div><span class="d-sm-none mobile-search"><i data-feather="search"></i></span>--}}
{{--                                </div>--}}
{{--                                <div class="Typeahead-menu"></div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </form>--}}
                </li>
{{--                <li class="onhover-dropdown"><a class="txt-dark" href="index.html#">--}}
{{--                        <h6 style="color: #fff">EN</h6></a>--}}
{{--                    <ul class="language-dropdown onhover-show-div p-20">--}}
{{--                        <li><a href="index.html#" data-lng="en"><i class="flag-icon flag-icon-is"></i> English</a></li>--}}
{{--                        <li><a href="index.html#" data-lng="es"><i class="flag-icon flag-icon-um"></i> Spanish</a></li>--}}
{{--                        <li><a href="index.html#" data-lng="pt"><i class="flag-icon flag-icon-uy"></i> Portuguese</a></li>--}}
{{--                        <li><a href="index.html#" data-lng="fr"><i class="flag-icon flag-icon-nz"></i> French</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}
                <li class="onhover-dropdown">
                    <div class="media align-items-center"><img class="align-self-center pull-right img-50 rounded-circle"
                                                               src="{{auth()->user()->image ?: '/admin_main/images/user.jpg'}}" alt="header-user">
                    </div>
                    <ul class="profile-dropdown onhover-show-div p-20" style="top:37px">
                        <li><a href="{{route('admin.profile.index')}}"><i data-feather="user"></i>{{__('Edit')}}</a></li>
{{--                        <li><a href="index.html#"><i data-feather="mail"></i>                                    Inbox</a></li>--}}
{{--                        <li><a href="index.html#"><i data-feather="lock"></i>                                    Lock Screen</a></li>--}}
{{--                        <li><a href="index.html#"><i data-feather="settings"></i>                                    Settings</a></li>--}}
                        <li><a href="{{route('admin.logout')}}"><i data-feather="log-out"></i> {{__('Logout')}}</a></li>
                    </ul>
                </li>
            </ul>
            <div class="d-lg-none mobile-toggle pull-right"><i data-feather="more-horizontal"></i></div>
        </div>
        <script id="result-template" type="text/x-handlebars-template">
            <div class="ProfileCard u-cf">
                <div class="ProfileCard-avatar"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay m-0"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg></div>
                <div class="ProfileCard-details">
                    <div class="ProfileCard-realName"></div>
                </div>
            </div>
        </script>
        <script id="empty-template" type="text/x-handlebars-template">
            <div class="EmptyMessage">Your search turned up 0 results. This most likely means the backend is down, yikes!</div>

        </script>
    </div>
</div>
<!-- Page Header Ends -->